# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TouringNW' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TouringNW
pod 'GoogleMaps'
pod 'GooglePlaces'

  target 'TouringNWTests' do
    inherit! :search_paths
    # Pods for testing
pod 'GoogleMaps'
pod 'GooglePlaces'
  end

  target 'TouringNWUITests' do
    inherit! :search_paths
    # Pods for testing
pod 'GoogleMaps'
pod 'GooglePlaces'
  end

end
